type: order_cards
visible: false
header: Matrix Product
text: >
  Reorder the matrix product operations in the optimal

  order:


  $$A_{5 \times 10} \  B_{10 \times 2}\ C_{2 \times 30}\ D_{30 \times 3}\ E_{3
  \times 9}$$
shuffle: true
score: 1
quiz:
  variants:
    - text: $AB$
    - text: $DE$
    - text: $BC$
    - text: $CD$
answer:
  - c4ca4238a0b923820dcc509a6f75849b
  - c81e728d9d4c2f636f067f89cc14862c
  - eccbc87e4b5ce2fe28308fd9f2a7baf3
  - cfcd208495d565ef66e7dff9f98764da
