type: code
visible: false
score: 30
code:
  - .laborantum/texts/course/2-Fully-Connected-NNs/2-Autoencoder/task.ipynb
  - .laborantum/src/models/feedforward/autoencoder.py
run:
  - jupyter-execute "${relativeTaskPath}/task.ipynb"
  - cd "${relativeTaskPath}/dist"; python task.py
  - mv "${relativeTaskPath}/dist/.answer.json" "${relativeTaskPath}/.solution.json"
  - python .laborantum/utils/checker.py -t "${relativeTaskPath}"
  - rm "${relativeTaskPath}/.answer.json"
  - rm "${relativeTaskPath}/.solution.json"
