type: order_cards
visible: false
header: Derivative of Sinus
text: Order cards to get proof of derivative of sinus
shuffle: true
score: 1
quiz:
  variants:
    - text: >
        Secondly, for small values of $dx$ (due to the same reason): 

        $$\cos(dx) = \sqrt{1 - \sin^2 dx} \approx \sqrt{1 - dx^2} \approx 1 -
        \frac{dx^2}{2}$$
    - text: |
        $dx$ in enumerator and in denominator cancels:
        $$- \frac{dx}{2} \sin(x) + \cos(x)$$
    - text: >
        Substitute the approximations into the expression:

        $$\frac{\sin(x) \left(1 - \frac{dx^2}{2}\right) + \cos(x) dx -
        \sin(x)}{dx}$$
    - text: |
        For small values of $dx$ first term is negligible:
        $$\cos(x)$$
    - text: |
        Firstly, for small values of $dx$ (The First Wonderful Limit): 
        $$\sin(dx) \approx dx$$
    - text: |
        The first and the last term cancels:
        $$\frac{- \frac{dx^2}{2} \sin(x) + \cos(x) dx}{dx}$$
    - text: |
        Expaning the first term in the enumerator:
        $$\frac{\sin(x) \cos(dx) + \cos(x) \sin(dx) - \sin(x)}{dx}$$
    - text: |
        Use formula of sinus of sum:
        $$\sin(a + b) = \sin(a) \cos(b) + \cos(a) \sin(b)$$
        to expand the first term in the enumerator.
    - text: >
        Take derivative of a function and insert $f(x) = \sin (x)$:

        $$\frac{d f(x)}{dx} = \frac{f(x + dx) - f(x)}{dx} = \frac{\sin(x + dx) -
        \sin(x)}{dx}$$
    - text: |
        Simplify the expression:
        $$\frac{\sin(x) - \frac{dx^2}{2} \sin(x) + \cos(x) dx - \sin(x)}{dx}$$
    - text: |
        So, the derivative of $\sin(x)$ is $\cos(x)$:
        $$\frac{d \sin(x)}{dx} = \cos(x)$$
answer:
  - c9f0f895fb98ab9159f51fd0297e236d
  - 8f14e45fceea167a5a36dedd4bea2543
  - 1679091c5a880faf6fb5e6087eb1b2dc
  - a87ff679a2f3e71d9181a67b7542122c
  - cfcd208495d565ef66e7dff9f98764da
  - c81e728d9d4c2f636f067f89cc14862c
  - 45c48cce2e2d7fbdea1afc51c7c6ad26
  - e4da3b7fbbce2345d7772b0674a318d5
  - c4ca4238a0b923820dcc509a6f75849b
  - eccbc87e4b5ce2fe28308fd9f2a7baf3
  - d3d9446802a44259755d38e6d163e820
