type: order_cards
visible: false
header: Derivative of Power Function
text: Order the cards to get proof of derivative of power function
shuffle: true
score: 1
quiz:
  variants:
    - text: >
        Start with the definition of derivative of a function and insert power
        function:


        $$\frac{df}{dx} = \frac{f(x + dx) - f(x)}{dx}= 

        \frac{(x + dx)^k - x^k}{dx}$$
    - text: >
        First and last termns cancel out:

        $$\frac{k x^{k - 1} dx + \frac{k (k - 1)}{2} x^{k - 2} (dx)^2 + \dots +
        (dx)^k}{dx}$$
    - text: >
        Open first bracket:

        $$\frac{x^k + k x^{k - 1} dx + \frac{k (k - 1)}{2} x^{k - 2} (dx)^2 +
        \dots + (dx)^k - x^k}{dx}$$
    - text: |
        So, the derivative of power function is:
        $$\frac{d x^k}{dx} = k x^{k - 1}$$
    - text: >
        Due to infinitisemality of $dx$ all terms except first one are
        negligible:

        $$k x^{k - 1}$$
    - text: |
        $dx$ in denominator cancels out:
        $$k x^{k - 1} + k (k - 1) x^{k - 2} dx + \dots + (dx)^{k - 1}$$
answer:
  - cfcd208495d565ef66e7dff9f98764da
  - c81e728d9d4c2f636f067f89cc14862c
  - c4ca4238a0b923820dcc509a6f75849b
  - e4da3b7fbbce2345d7772b0674a318d5
  - a87ff679a2f3e71d9181a67b7542122c
  - eccbc87e4b5ce2fe28308fd9f2a7baf3
